name: "automatic kibot generation and deployment"

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  cicd:
    name: "KiBot (action)"
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: run kibot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: nixie.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'nixie.kicad_sch'
        # optional - PCB design file
        board: 'nixie.kicad_pcb'
        install3D: YES
    
    - name: upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: automatic_output
        path: output

# This step is to upload the results to the gh-pages branche and publish the page
  deploy:
    runs-on: ubuntu-latest
    needs: cicd

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve results
      uses: actions/download-artifact@v4
      with:
        name: automatic_output
        path: output

    - name: Disable Jekyll
      # Jekyll will filter the KiRi folders
      run: |
        touch output/.nojekyll

    - name: Deploy navigate results
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: output
        #repository-name: INTI-CMNB/kibot_variants_arduprog_site
        #token: ${{ secrets.TOKEN }}
