name: "automatic kibot generation and deployment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    name: "KiBot (action)"
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: run kibot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        # Required - kibot config file
        config: nixie.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'nixie.kicad_sch'
        # optional - PCB design file
        board: 'nixie.kicad_pcb'
        install3D: YES
    
    - name: upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: automatic_output
        path: output
