name: "automatic kibot generation on pcb changes"

on:
  push:
    branches:
      - main
    paths: 
      - '**/*.kicad_pcb'
  pull_request:
    branches:
      - main
    paths: 
      - '**/*.kicad_pcb'
  workflow_dispatch:

jobs:
  cicd:
    name: "KiBot PCB (action)"
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: run kibot
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: .kibot/pcb_only.kibot.yaml
        dir: output
        board: 'nixie.kicad_pcb'
        install3D: YES
        
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: pcb
        path: output